import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <nav className="flex justify-evenly gap-3">
          <Link href="/">Home</Link>
          <Link href="/champions">챔피언 목록</Link>
          <Link href="/items">아이템 목록</Link>
          <Link href="/rotation">챔피언 로테이션</Link>
        </nav>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
